language: en

pipeline:
  - name: WhitespaceTokenizer
    case_sensitive: false
  - name: RegexFeaturizer
    case_sensitive: false
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2
    lowercase: true
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
    case_sensitive: false
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
    loss_type: cross_entropy
    similarity_type: auto
    ranking_length: 10
    maximum_positive_similarity: 0.8
    maximum_negative_similarity: -0.4
    # Simplified settings (no transformer)
    entity_recognition: true
    intent_classification: true
    use_sparse_features: true
    use_dense_features: true
    drop_rate: 0.2
    weight_sparsity: 0.8
    evaluate_every_number_of_epochs: 20
  - name: EntitySynonymMapper
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: true
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax

  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
    model_confidence: softmax
    loss_type: cross_entropy
    similarity_type: auto
    ranking_length: 10
    maximum_positive_similarity: 0.8
    maximum_negative_similarity: -0.4
    drop_rate: 0.2
    weight_sparsity: 0.8
    evaluate_every_number_of_epochs: 20
    use_sparse_features: true
    use_dense_features: true
    entity_recognition: false
    intent_classification: false
assistant_id: 20251001-202719-tall-plate
